import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { ThemeWrapper } from "@/context"; 
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <div className="container" >
        <Navbar/>
          <ThemeWrapper>
          <div className="wrapper">{children}</div>
          </ThemeWrapper>
          <Footer/>
        </div>
        
      </body>
    </html>
  );
}
